name: Deploy to Pages
on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  test-build-and-deploy:
    name: Test, Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install
        run:
          npm install

      - name: Test
        run:
          npm run test

      - name: Build
        run:
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
